[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "drop-backend"
version = "0.1.0"
description = "A brief description of your package"
authors = ["Your Name <itissid@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "23.1.0"
aiohttp = "3.8.4"
aiosignal = "1.3.1"
altair = "5.0.1"
antlr4-python3-runtime = "4.9.3"
anyio = "3.6.2"
appnope = "0.1.3"
argon2-cffi = "21.3.0"
argon2-cffi-bindings = "21.2.0"
arrow = "1.2.3"
asgi-csrf = "0.9"
asgiref = "3.7.2"
asttokens = "2.2.1"
async-timeout = "4.0.2"
attrs = "23.1.0"
backcall = "0.2.0"
beautifulsoup4 = "4.12.2"
black = "23.3.0"
bleach = "6.0.0"
blinker = "1.5"
blis = "0.7.9"
braceexpand = "0.1.7"
cachetools = "5.3.1"
catalogue = "2.0.8"
certifi = "2023.5.7"
cffi = "1.15.1"
cfgv = "3.3.1"
charset-normalizer = "3.1.0"
click = "8.1.3"
click-default-group-wheel = "1.2.2"
colorama = "0.4.6"
comm = "0.1.3"
confection = "0.0.4"
contexttimer = "0.3.3"
contourpy = "1.0.7"
cycler = "0.11.0"
cymem = "2.0.7"
dataclasses-json = "0.5.9"
datasette = "0.64.3"
datasette-faiss = "0.2"
debugpy = "1.6.7"
decorator = "5.1.1"
defusedxml = "0.7.1"
distlib = "0.3.6"
einops = "0.6.1"
exceptiongroup = "1.1.1"
executing = "1.2.0"
fairscale = "0.4.4"
faiss-cpu = "1.7.4"
fastjsonschema = "2.17.1"
filelock = "3.12.0"
fonttools = "4.39.4"
fqdn = "1.5.1"
frozenlist = "1.3.3"
fsspec = "2023.5.0"
ftfy = "6.1.1"
gitdb = "4.0.10"
gitpython = "3.1.31"
h11 = "0.14.0"
h2 = "4.1.0"
hpack = "4.0.0"
httpcore = "0.17.3"
httpx = "0.24.1"
huggingface-hub = "0.15.1"
hupper = "1.12"
hypercorn = "0.14.3"
hyperframe = "6.0.1"
identify = "2.5.24"
idna = "3.4"
imageio = "2.31.0"
importlib-metadata = "6.6.0"
iniconfig = "2.0.0"
install = "1.3.5"
iopath = "0.1.10"
ipdb = "0.13.13"
ipykernel = "6.23.1"
ipython-genutils = "0.2.0"
ipywidgets = "8.0.6"
isoduration = "20.11.0"
itsdangerous = "2.1.2"
janus = "1.0.0"
jedi = "0.18.2"
jinja2 = "3.1.2"
jsonpath-ng = "1.5.3"
jsonpointer = "2.3"
jsonschema = "4.17.3"
jupyter = "1.0.0"
jupyter-console = "6.6.3"
jupyter-events = "0.6.3"
jupyter-client = "8.2.0"
jupyter-core = "5.3.0"
jupyter-server = "2.5.0"
jupyter-server-terminals = "0.4.4"
jupyterlab-pygments = "0.2.2"
jupyterlab-widgets = "3.0.7"
kaggle = "1.5.13"
kiwisolver = "1.4.4"
langcodes = "3.3.0"
lazy-loader = "0.2"
markdown-it-py = "2.2.0"
markupsafe = "2.1.2"
marshmallow = "3.19.0"
marshmallow-enum = "1.5.1"
matplotlib = "3.7.1"
matplotlib-inline = "0.1.6"
mdurl = "0.1.2"
mergedeep = "1.3.4"
mistune = "2.0.5"
mpmath = "1.3.0"
multidict = "6.0.4"
murmurhash = "1.0.9"
mypy = "1.4.0"
mypy-extensions = "1.0.0"
nbclassic = "1.0.0"
nbclient = "0.8.0"
nbconvert = "7.4.0"
nbformat = "5.8.0"
nest-asyncio = "1.5.6"
networkx = "3.1"
nodeenv = "1.8.0"
notebook = "6.5.4"
notebook-shim = "0.2.3"
numpy = "1.24.3"
omegaconf = "2.3.0"
openai = "0.27.7"
opencv-python-headless = "4.5.5.64"
opendatasets = "0.1.22"
openrouteservice = "2.3.3"
packaging = "23.1"
pandas = "2.0.2"
pandocfilters = "1.5.0"
parso = "0.8.3"
pathspec = "0.11.1"
pathy = "0.10.1"
pexpect = "4.8.0"
pickleshare = "0.7.5"
pillow = "9.5.0"
platformdirs = "3.5.1"
plotly = "5.15.0"
pluggy = "1.2.0"
ply = "3.11"
portalocker = "2.7.0"
pre-commit = "3.3.2"
preshed = "3.0.8"
priority = "2.0.0"
prometheus-client = "0.16.0"
prompt-toolkit = "3.0.38"
protobuf = "4.23.2"
psutil = "5.9.5"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
pyarrow = "12.0.0"
pycocoevalcap = "1.2"
pycocotools = "2.0.6"
pycparser = "2.21"
pydantic = "1.10.9"
pydeck = "0.8.1b0"
pygments = "2.15.1"
pylance = "0.5.4"
pympler = "1.0.1"
pyparsing = "3.0.9"
pyrsistent = "0.19.3"
pytest = "7.4.0"
python-dateutil = "2.8.2"
python-json-logger = "2.0.7"
python-magic = "0.4.27"
python-multipart = "0.0.6"
python-slugify = "8.0.1"
pytz = "2023.3"
pytz-deprecation-shim = "0.1.0.post0"
pywavelets = "1.4.1"
pyyaml = "6.0"
pyzmq = "25.0.2"
qtconsole = "5.4.3"
qtpy = "2.3.1"
quart = "0.18.4"
quart-cors = "0.6.0"
regex = "2023.5.5"
requests = "2.31.0"
rfc3339-validator = "0.1.4"
rfc3986-validator = "0.1.1"
rich = "13.4.1"
safetensors = "0.3.1"
scikit-image = "0.21.0"
send2trash = "1.8.2"
sentencepiece = "0.1.99"
six = "1.16.0"
smart-open = "6.3.0"
smmap = "5.0.0"
sniffio = "1.3.0"
soupsieve = "2.4.1"
spacy-legacy = "3.0.12"
spacy-loggers = "1.0.4"
sqlalchemy = "2.0.18"
sqlalchemy-utils = "0.41.1"
sqlite-fts4 = "1.0.3"
sqlite-utils = "3.33"
srsly = "2.4.6"
stack-data = "0.6.2"
sympy = "1.12"
tabulate = "0.9.0"
tenacity = "8.2.2"
terminado = "0.17.1"
text-unidecode = "1.3"
thinc = "8.1.10"
tifffile = "2023.4.12"
tiktoken = "0.4.0"
timm = "0.4.12"
tinycss2 = "1.2.1"
tokenizers = "0.13.3"
toml = "0.10.2"
tomli = "2.0.1"
toolz = "0.12.0"
torch = "2.0.1"
torchvision = "0.15.2"
tornado = "6.3.2"
tqdm = "4.65.0"
traitlets = "5.9.0"
transformers = "4.30.0"
types-requests = "2.31.0.1"
types-urllib3 = "1.26.25.13"
typing-inspect = "0.9.0"
typing-extensions = "4.6.3"
tzdata = "2023.3"
tzlocal = "4.3"
uri-template = "1.2.0"
urllib3 = "2.0.2"
uvicorn = "0.22.0"
validators = "0.20.0"
virtualenv = "20.23.0"
wasabi = "1.1.2"
wcwidth = "0.2.6"
webcolors = "1.13"
webdataset = "0.2.48"
webencodings = "0.5.1"
websocket-client = "1.5.2"
werkzeug = "2.3.4"
widgetsnbextension = "4.0.7"
wsproto = "1.2.0"
yarl = "1.9.2"
zipp = "3.15.0"
time-uuid = "^0.2.0"
typer = "^0.9.0"
alembic = "^1.11.3"

[tool.poetry.dev-dependencies]

